taikoxyz/trailblazer-adapters

adapters/projects/gaming/whitelist.go, cmd/root.go, cmd/transaction_sender.go
---
---
adds gaming whitelist for trail 7
---
---
---
=> feat: gaming whitelist

adapters/projects/gaming/whitelist.go
=> feat(gaming-adapters): adding contracts crack and stack

adapters/projects/gaming/whitelist.go, whitelist/whitelist.go
=> Added brigade entry in whitelist.go

adapters/projects/gaming/whitelist.go
Added Robots.Farm
---
---
---
---
---
=> Add Robots.Farm to whitelist.go 

whitelist/whitelist.go
Rubic contracts: https://github.com/Cryptorubic/multi-proxy-rubic/blob/master/deployments/taiko.json
Submitted by @renedsaa at telegram.
---
---
Adding Rubic Contracts to the whitelist for taiko trailblazer program. Contacts taken from Rubic official github: https://github.com/Cryptorubic/multi-proxy-rubic/blob/master/deployments/taiko.json
Adding Rubic Contracts to the whitelist for taiko trailblazer program. 
---
- [Yes] I have followed the conventional commit messages standard.
- [Yes] Any whitelisted contracts added are verified.
---
---
=>  Adding Rubic to the whitelist

abigen.sh, adapters/blocks.go, adapters/contracts/erc20/erc20.go, adapters/contracts/ritsu/ritsu.go, adapters/logs.go, adapters/projects/ritsu/transfer_event.go, cmd/process_log.go, cmd/ritsu_lp.go, cmd/root.go, erc20.json, go.mod, go.sum, ritsu.json
---
---
index transfers of ritsu LP tokens, giving breakdown of each token at point of transfer
---
---
---
=> feat: index ritsu LP token transfers

adapters/projects/izumi/transfer_event.go, adapters/projects/ritsu/transfer_event.go
=> fix: nil check

adapters/logs.go, adapters/projects/izumi/transfer_event.go, adapters/projects/ritsu/transfer_event.go, cmd/lp.go, cmd/process_log.go
=> fix: stake event

adapters/projects/izumi/transfer_event.go, cmd/lp.go
=> feat: check for deposit event

whitelist/whitelist.go
=> Update for OKX Market

whitelist/whitelist.go
=> Update for Revox Lense

whitelist/whitelist.go
Bullishs New Contract Updated.
---
---
---
---
---
=> Update whitelist.go with bullishs contract

whitelist/whitelist.go
Adds Rubyscore Deposit contract
=> feat(whitelist): add deposit contract

whitelist/whitelist.go
---
This PR will add [Swing](https://www.swing.xyz) contract to whitelist
---
=> feat(whitelist): add swing for taiko

adapters/projects/gaming/whitelist.go
=> fix: dup contracts

whitelist/whitelist.go
---
`feat(whitelist): add OpenALCHI contract to the whitelist`
---
This PR adds the contract address for the OpenALCHI project to the Taiko Network whitelist. The contract is used for managing OpenALCHI-related interactions on the network, ensuring integration with the whitelist requirements.
---
---
The OpenALCHI project is an NFT game deployed on multiple blockchains, including Taiko. This PR is part of the effort to integrate the project fully with Taiko's ecosystem.
---
=> feat(whitelist): add OpenALCHI contract to the whitelist

whitelist/whitelist.go
---
*feat(whitelist): Add magpie to whitelist*
---
Add the Magpie Protocol Taiko network contract to whitelist
---
---
---
=> feat(whitelist): Add magpie to whitelist

adapters/adapters.go, adapters/projects/drips/lock.go, adapters/projects/drips/lock_test.go, adapters/projects/symmetric/lock.go, adapters/projects/symmetric/lock_test.go
=> feat: add duration

whitelist/protocols.json
---
feat(whitelist): Add Symmetric Taiko locking contract
---
Add the Taiko LP locking contract and reward distributor
---
---
---
=> feat(whitelist): Add Symmetric Taiko locking contract

adapters/projects/gaming/gaming.go
=> Update gaming.go Robots.Farm

whitelist/protocols.json
=> fix: update contracts

whitelist/protocols.json
=> add-logo-twitter-magpieprotocol

whitelist/protocols.json
=> add owlto new address

whitelist/protocols.json
=> feat(whitelist): add IceCreamSwap DEX and DEX aggregator contracts for taiko

adapters/projects/robinos/prediction.go
=> More events in for robinos

adapters/projects/robinos/prediction.go
=> Modified Robinos Events

adapters/projects/robinos/prediction.go
=> Add 4 new events robinos

adapters/projects/robinos/prediction.go
=> updated robinos event list

adapters/projects/robinos/prediction.go
=> New multiplier events for Robinos

adapters/adapters.go
=> feat: logx type

adapters/projects/robinos/prediction.go
=> Rosbinos multiplier events

adapters/projects/robinos/prediction.go
=> New Robinos Events

whitelist/protocols.json
=> Added third contract to rupture labs 3rd game

whitelist/protocols.json
---
*add new Astrotrove contract address*
---
add explorer contract for game 
---
---
=> chore(whitelist): add new Astrotrove contract address

adapters/adapters.go, adapters/projects/avalon/claim.go, adapters/projects/avalon/claim_test.go, cmd/adapter.go, cmd/cmd.go
Set avalon airdrop/claim and token contract once public. But can be merged before.
=> feat: avalon airdrop

whitelist/protocols.json
feat(whitelist): add Pheasant Network's bridge contract for Taiko
---
Added Pheasant Network contract address listed on Trailblazers Ecosystem page.
---
---
I was in contact with Nicky and Swarnabha from the Taiko team.
=> feat(whitelist): add Pheasant Network's bridge contract for Taiko
